# -*- coding: utf-8 -*-
"""InvestingOOP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzWhUEhbpwBR3jWkv4QtJhsQcVzkShSa

### Imports
"""

import random
from IPython.display import clear_output

"""### Investor Class"""

class Investor:
  def __init__(self, name, budget, isHumen):
    self.name= name
    self.budget= budget
    self.properties=[]
    self.isHumen=isHumen

  def BuyHouse(self, market): #make acquisition
    if self.isHumen:
      print("Please choose a property below: ")
      market.Print()  #show properties
      i= int(input())-1
    else:
      #randomly buy house
      i = random.randint(0, len(market.properties)-1)
    self.budget-=market.properties[i].price #subtruct house price from investor budget
    self.properties.append(market.properties[i]) #add property to investors properties
    print('self.properties: ',self.properties[len(self.properties)-1].location)
    print('******************************')
    print(f'money left: {self.budget}$')
    print(f'The house in {self.properties[len(self.properties)-1].location} has been sold to {self.name}')
    print('******************************\n')
    del market.properties[i]

  def ShowProperty(self):
    i=1
    for prop in self.properties:
      print(f'{i} location:{prop.location}, Price:{prop.price}')
      i+=1

"""### House Class"""

class House:
  def __init__(self, location, price, width, length):
    self.location=location
    self.price=price
    self.width= width
    self.length=length
  def Calc(self):
    self.size= width*length

"""### Market Class"""

class Market:
  def __init__(self, properties):
    self.properties=properties

  def HouseSold(self, choice, name):
    print('HouseSold')

  def Print(self):
    print('Houses left in the market:\n')
    i=1
    for prop in self.properties:
      print(f'{i}. {prop.location} Price: {prop.price}$\n')
      i+=1
  
  def ChangePrices(self, invs):
    self.__ChangeMarket(self.properties)
    for inv in invs:
      self.__ChangeMarket(inv.properties)

  def SellBackToMarket(self, houseIndex, invs):
      for inv in invs:
        if not inv.isHumen:
          houseIndex=random.randint(1,3)
          if houseIndex==3:
            houseIndex=0
          else:
            houseIndex=random.randint(0,len(inv.properties)-1)
        print('houseIndex: ',houseIndex)
        print(f'{inv.name} sold house in {inv.properties[houseIndex].location}')
        print(f'Prev budget: {inv.budget}$')
        self.properties.append(inv.properties[houseIndex])
        inv.budget+= inv.properties[houseIndex].price
        del inv.properties[houseIndex]
        print(f'New budget: {inv.budget}$')

  def __ChangeMarket(self, houses):
    for house in houses:
        if random.randint(0, 1)==1:
          house.price+=0.15*house.price
        else:
          house.price-=0.15*house.price

"""### **Main**"""

def printMenu():
  print('\n_________________________\n'+
        '1. Show market values\n'+
        '2. Buy a property\n'+
        '3. Sell a property\n'+
        '4. Show my properties\n'+
        '5. Exit\n')
  
def ShowMarketValues(market,investors):
  market.Print()

def BuyAProperty(market,investors):
  for inv in investors:
    inv.BuyHouse(market)
    market.ChangePrices(investors)
  input('Press any key to continue...')

def SellAProperty(market,investors):
      print('Choose the house you want to sell: ')
      investors[0].ShowProperty()
      houseIndex= int(input())-1
      market.SellBackToMarket(houseIndex, investors)
      market.ChangePrices(investors)

def ShowMyProperties(market,investors):
  for inv in investors:
    print(f'{inv.name} properties are these:\n')
    for house in inv.properties:
      print(f'house in: {house.location}')
    print('********************************\n')
def MySC(case, market,investors):
  switcher={
      '1': ShowMarketValues,
      '2': BuyAProperty,
      '3': SellAProperty,
      '4': ShowMyProperties,
      }
  func = switcher.get(case, lambda market, investors: 'Invalid')
  return func(market,investors)

def Main():
  name= input('hello please enter your name: ')
  budget= input('please enter your budget: ')
  investors=[Investor(name,int(budget),True),Investor('Harry',10000,False), Investor('Potter',20000,False)]
  houses = [
            House("LA, California",450000,20,10),
            House("IL, Tel Aviv",1000000,5,5),
            House("Rus, Moscow",40000,20,10),
            House("Switz, Zr",125000,7,9),
            House("Fr, Paris",225000,15,4),
            House("Eg, Cairo",75000,15,15),
            House("Pt, Lisbon",100000,10,10),
            House("Ge, Batumi",75000,14,6),
            House("In, New Delhi",50000,20,20),
            House("Ca, Montreal",500000,30,35),
            House("Cambodia, Phnom Pen",15000,9,9),
            House("Uk, London",1000000,10,10)
            ]
  m= Market(houses)
  choice=0
  while int(choice)!= 5:
    printMenu()   
    choice=input()
    if choice =='5':
      for inv in investors:
        print(f"{inv.name}'s budget-> {inv.budget}$\n")
        for house in inv.properties:
          print('Properties:')
          print(f'{house.location}\n The house price is: {house.price}\n And the size in square meters is: {house.Calc()}')
          print('********************************')
      print('ByeBye!')
      break

    if MySC(choice, m, investors)== "Invalid":
      print('Wrong Choice!')
    input('\nPress any key to continue...')
    clear_output()

Main()